Repository apache/incubator-heron, pull requests merged in 2020-11, with the labels that each got.

#3628 Added some helpful Bookkeeper config items
  deploy/kubernetes/helm/templates/bookie.yaml
  deploy/kubernetes/helm/values.yaml.template
Labels: Kubernetes

#3598 Use click instead of argparse in py instance
  heron/executor/src/python/heron_executor.py
  heron/instance/src/python/BUILD
  heron/instance/src/python/__init__.py
  heron/instance/src/python/instance.py
  heron/instance/src/python/instance/__init__.py
Labels: PyHeron

#3597 Clean heron-ui backend
  heron/common/src/python/utils/__init__.py
  heron/instance/src/python/utils/__init__.py
  heron/shell/src/python/BUILD
  heron/tools/common/src/python/BUILD
  heron/tools/common/src/python/access/__init__.py
  heron/tools/common/src/python/access/fetch.py
  heron/tools/common/src/python/access/heron_api.py
  heron/tools/common/src/python/access/query.py
  heron/tools/common/src/python/access/tracker_access.py
  heron/tools/common/src/python/clients/__init__.py
  heron/tools/common/src/python/clients/tracker.py
  heron/tools/explorer/src/python/BUILD
  heron/tools/explorer/src/python/logicalplan.py
  heron/tools/explorer/src/python/main.py
  heron/tools/explorer/src/python/physicalplan.py
  heron/tools/explorer/src/python/topologies.py
  heron/tools/explorer/tests/python/explorer_unittest.py
  heron/tools/ui/resources/static/js/stat-trendlines.js
  heron/tools/ui/resources/static/js/topologies.js
  heron/tools/ui/resources/templates/application.html
  heron/tools/ui/resources/templates/browse.html
  heron/tools/ui/resources/templates/config.html
  heron/tools/ui/resources/templates/error.html
  heron/tools/ui/resources/templates/exception.html
  heron/tools/ui/resources/templates/file.html
  heron/tools/ui/resources/templates/nav.html
  heron/tools/ui/resources/templates/shell.snip.html
  heron/tools/ui/resources/templates/topologies.html
  heron/tools/ui/resources/templates/topology.html
  heron/tools/ui/src/python/BUILD
  heron/tools/ui/src/python/args.py
  heron/tools/ui/src/python/consts.py
  heron/tools/ui/src/python/handlers/__init__.py
  heron/tools/ui/src/python/handlers/api/__init__.py
  heron/tools/ui/src/python/handlers/api/metrics.py
  heron/tools/ui/src/python/handlers/api/topology.py
  heron/tools/ui/src/python/handlers/base.py
  heron/tools/ui/src/python/handlers/common/consts.py
  heron/tools/ui/src/python/handlers/common/utils.py
  heron/tools/ui/src/python/handlers/mainhandler.py
  heron/tools/ui/src/python/handlers/notfound.py
  heron/tools/ui/src/python/handlers/ranges.py
  heron/tools/ui/src/python/handlers/topology.py
  heron/tools/ui/src/python/main.py
  integration_test/src/python/http_server/BUILD
  integration_test/src/python/local_test_runner/test_explorer.py
  vagrant/Vagrantfile
Labels: ui

#3630 Upgrade to Bazel 3.7
  .bazelversion
  .travis.yml
  README.md
  docker/compile/Dockerfile.centos7
  docker/compile/Dockerfile.debian10
  docker/compile/Dockerfile.debian9
  docker/compile/Dockerfile.ubuntu18.04
  docker/compile/Dockerfile.ubuntu20.04
  docker/test/Dockerfile.centos7
  docker/test/Dockerfile.ubuntu18.04
  scripts/ci/setup_bazel.sh
  vagrant/init.sh
  website2/docs/compiling-osx.md
  website2/website/scripts/Dockerfile.ubuntu18.04
  website2/website/scripts/replace.js
  website2/website/versioned_docs/version-0.20.2-incubating/compiling-osx.md
Labels: build

#3634 Fixes to heron-ui arg name changes
  deploy/kubernetes/general/tools.yaml
  deploy/kubernetes/helm/templates/tools.yaml
  deploy/kubernetes/helm/values.yaml.template
  deploy/kubernetes/minikube/tools.yaml
  website2/docs/user-manuals-heron-ui.md
  website2/website/versioned_docs/version-0.20.0-incubating/user-manuals-heron-ui.md
Labels: ui

#3635 Adding quotes around value that Helm was changing to scientific notation
  deploy/kubernetes/helm/templates/bookie.yaml
Labels: Kubernetes

#3637 Typo fix in HeronPy examples comment
  examples/src/python/__init__.py
Labels: PyHeron
