Repository apache/incubator-heron, pull requests merged in 2022-05, with the labels that each got.

#3825 [3821] Remove deprecated Host Path, NFS, and EBS support for Kubernetes
  heron/schedulers/src/java/org/apache/heron/scheduler/kubernetes/KubernetesContext.java
  heron/schedulers/src/java/org/apache/heron/scheduler/kubernetes/V1Controller.java
  heron/schedulers/src/java/org/apache/heron/scheduler/kubernetes/Volumes.java
  heron/schedulers/tests/java/org/apache/heron/scheduler/kubernetes/V1ControllerTest.java
  heron/schedulers/tests/java/org/apache/heron/scheduler/kubernetes/VolumesTests.java
Labels: Kubernetes

#3832 Update rules-scala of Scala
  WORKSPACE
  tools/bazel.rc
Labels: build

#3831 Added to show the number of instances in the topology list UI.
  heron/tools/tracker/src/python/topology.py
  heron/tools/tracker/tests/python/mock_proto.py
  heron/tools/tracker/tests/python/topology_unittest.py
  heron/tools/ui/resources/static/js/alltopologies.js
  heron/tools/ui/resources/templates/topology.html
Labels: enhancement, ui

#3836 Reduce the DEBUG log
  heron/common/src/python/utils/log.py
  heron/tools/tracker/src/python/metricstimeline.py
Labels: enhancement
